name: Update alpha
on:
  workflow_run:
    workflows:
      - Release
    branches:
      - master
    types: completed
jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Rebase alpha to master
        run: |
            git fetch --unshallow
            git checkout alpha
            git rebase origin/master
            git push
